name: pub_release
version: 1.0.12
homepage: https://github.com/bsutton/pub_release
description: Automates the release of a dart package to pub.dev including running dartfmt, creating a git tag, incrementing the packages version no. and pushing the package to pub.dev.
environment: 
  sdk: '>=2.8.1 <3.0.0'
dependencies: 
  dshell: ^1.0.0
  pub_semver: ^1.0.0
  meta: ^1.2.2
dev_dependencies: 
  pedantic: ^1.9.0
  test: ^1.14.4
  github: ^7.0.1
dependency_overrides: 
  github: 
    path: ../github.dart
executables: 
  pub_release: pub_release
